const $=id=>document.getElementById(id),clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
let initial={};try{initial=JSON.parse(document.getElementById("pump-initial-data")?.textContent||"{}")}catch{}
const state={lang:localStorage.getItem("pp_lang")||"en",profile:localStorage.getItem("pp_profile")||"strict",live:initial.live||null,result:initial.backtest||null,entryPrice:Number(localStorage.getItem("pp_entry_price"))||0,tab:"pulse"};
const copy={
  en:{readyData:"DATA READY",offline:"RETRYING",modelTitle:"Mathematical PUMP model",warning:"Research page only. No orders or profit guarantees. Every investment decision is made at your own risk.",closed:"CLOSED 30-MIN CANDLES",readiness:"READINESS",wait:"WAIT",buySetup:"BUY SETUP",blocked:"BLOCKED",prepared:"The latest complete market calculation is prepared.",profile:"Profile",strict:"Strict",active:"Active",activity:"Activity",flow:"Buyer flow",agreement:"Agreement",late:"Late risk",movement:"PUMP MOVEMENT",recent:"recent closed candles",buy:"BUY",sell:"SELL",notReady:"NOT READY",ready:"READY",noPosition:"NO POSITION",personal:"PERSONAL CALCULATION",sixMonths:"6-month PUMP test",testInfo:"Set your exchange costs. The server recalculates the same model on closed candles.",capital:"Capital",entryFee:"Entry fee",exitFee:"Exit fee",slippage:"Slippage",quick:"Quick",calculate:"CALCULATE 6 MONTHS",execution:"Signal after candle close → execution at next candle open.",calculating:"Server is calculating…",trades:"TRADES",profitable:"PROFITABLE",drawdown:"MAX. DRAWDOWN",fees:"FEES",tradeChart:"TRADE CHART",entries:"entries",exits:"exits",completed:"Completed trades",contactAuthor:"CONTACT THE AUTHOR",privateMessage:"Private message",contactInfo:"Leave a name or an email. Other visitors cannot see your message.",nameOptional:"Name (optional)",emailOptional:"Email (optional)",oneRequired:"Please provide at least a name or an email.",message:"Message",consent:"I agree that my details are stored to answer this message.",send:"SEND PRIVATELY",admin:"Author login / inbox",navPulse:"Pulse",navTest:"6M test",navContact:"Contact",lateMove:"Late move — do not chase",upward:"Upward expansion",downward:"Downward expansion",calm:"Calm breathing",transition:"Transition state",signal:"Stages {n}/4 · RSI {rsi} · 36h {dd}%",period:"{from} — {to}",tradeOf:"Trade {n} of {all}",entry:"ENTRY",exit:"EXIT",why:"WHY ENTRY / EXIT",noTrades:"No completed trades in this period.",sent:"Message sent privately.",sendError:"Could not send. Check the form and try again.",sending:"Sending…",testError:"Calculation is temporarily unavailable. Please try again."},
  de:{readyData:"DATEN BEREIT",offline:"NEUER VERSUCH",modelTitle:"Mathematisches PUMP-Modell",warning:"Nur Forschungsseite. Keine Orders und keine Gewinngarantie. Jede Anlageentscheidung erfolgt auf eigenes Risiko.",closed:"GESCHLOSSENE 30-MIN-KERZEN",readiness:"BEREITSCHAFT",wait:"WARTEN",buySetup:"KAUF-SETUP",blocked:"GESPERRT",prepared:"Die letzte vollständige Marktberechnung ist vorbereitet.",profile:"Profil",strict:"Vorsichtig",active:"Aktiv",activity:"Aktivität",flow:"Käuferfluss",agreement:"Übereinstimmung",late:"Spätrisiko",movement:"PUMP-BEWEGUNG",recent:"letzte geschlossene Kerzen",buy:"KAUF",sell:"VERKAUF",notReady:"NICHT BEREIT",ready:"BEREIT",noPosition:"KEINE POSITION",personal:"PERSÖNLICHE BERECHNUNG",sixMonths:"6-Monats-PUMP-Test",testInfo:"Börsenkosten einstellen. Der Server berechnet dasselbe Modell mit geschlossenen Kerzen.",capital:"Kapital",entryFee:"Einstiegsgebühr",exitFee:"Ausstiegsgebühr",slippage:"Slippage",quick:"Schnell",calculate:"6 MONATE BERECHNEN",execution:"Signal nach Kerzenschluss → Ausführung zur nächsten Eröffnung.",calculating:"Server berechnet…",trades:"GESCHÄFTE",profitable:"GEWINNER",drawdown:"MAX. RÜCKGANG",fees:"GEBÜHREN",tradeChart:"GESCHÄFTS-CHART",entries:"Einstiege",exits:"Ausstiege",completed:"Abgeschlossene Geschäfte",contactAuthor:"AUTOR KONTAKTIEREN",privateMessage:"Private Nachricht",contactInfo:"Name oder E-Mail genügt. Andere Besucher sehen die Nachricht nicht.",nameOptional:"Name (optional)",emailOptional:"E-Mail (optional)",oneRequired:"Bitte mindestens Name oder E-Mail angeben.",message:"Nachricht",consent:"Ich stimme der Speicherung meiner Angaben zur Beantwortung zu.",send:"PRIVAT SENDEN",admin:"Autoren-Login / Postfach",navPulse:"Puls",navTest:"6M-Test",navContact:"Kontakt",lateMove:"Späte Bewegung — nicht hinterherlaufen",upward:"Aufwärtsbewegung",downward:"Abwärtsbewegung",calm:"Ruhiger Markt",transition:"Übergangsphase",signal:"Stufen {n}/4 · RSI {rsi} · 36h {dd}%",period:"{from} — {to}",tradeOf:"Geschäft {n} von {all}",entry:"EINSTIEG",exit:"AUSSTIEG",why:"WARUM EINSTIEG / AUSSTIEG",noTrades:"Keine abgeschlossenen Geschäfte in diesem Zeitraum.",sent:"Nachricht wurde privat gesendet.",sendError:"Senden nicht möglich. Formular prüfen und erneut versuchen.",sending:"Wird gesendet…",testError:"Berechnung vorübergehend nicht verfügbar. Bitte erneut versuchen."},
  tr:{readyData:"VERİ HAZIR",offline:"YENİDEN DENİYOR",modelTitle:"Matematiksel PUMP modeli",warning:"Yalnızca araştırma sayfasıdır. Emir veya kâr garantisi yoktur. Her yatırım kararı kendi riskinizdedir.",closed:"KAPANMIŞ 30 DAKİKALIK MUMLAR",readiness:"HAZIRLIK",wait:"BEKLE",buySetup:"ALIM KURULUMU",blocked:"ENGELLENDİ",prepared:"Son tamamlanan piyasa hesaplaması hazır.",profile:"Profil",strict:"Temkinli",active:"Aktif",activity:"Aktivite",flow:"Alıcı akışı",agreement:"Uyum",late:"Geç giriş riski",movement:"PUMP HAREKETİ",recent:"son kapanan mumlar",buy:"AL",sell:"SAT",notReady:"HAZIR DEĞİL",ready:"HAZIR",noPosition:"POZİSYON YOK",personal:"KİŞİSEL HESAPLAMA",sixMonths:"6 aylık PUMP testi",testInfo:"Borsa masraflarını ayarlayın. Sunucu aynı modeli kapanmış mumlarla hesaplar.",capital:"Sermaye",entryFee:"Giriş ücreti",exitFee:"Çıkış ücreti",slippage:"Kayma",quick:"Hızlı",calculate:"6 AYI HESAPLA",execution:"Mum kapanışından sonra sinyal → sonraki mum açılışında işlem.",calculating:"Sunucu hesaplıyor…",trades:"İŞLEMLER",profitable:"KÂRLI",drawdown:"MAKS. DÜŞÜŞ",fees:"ÜCRETLER",tradeChart:"İŞLEM GRAFİĞİ",entries:"girişler",exits:"çıkışlar",completed:"Tamamlanan işlemler",contactAuthor:"YAZARLA İLETİŞİM",privateMessage:"Özel mesaj",contactInfo:"İsim veya e-posta yeterlidir. Diğer ziyaretçiler mesajı göremez.",nameOptional:"İsim (isteğe bağlı)",emailOptional:"E-posta (isteğe bağlı)",oneRequired:"Lütfen en az isim veya e-posta girin.",message:"Mesaj",consent:"Yanıt için bilgilerimin saklanmasını kabul ediyorum.",send:"ÖZEL GÖNDER",admin:"Yazar girişi / gelen kutusu",navPulse:"Nabız",navTest:"6A test",navContact:"İletişim",lateMove:"Geç hareket — peşinden koşma",upward:"Yukarı genişleme",downward:"Aşağı genişleme",calm:"Sakin piyasa",transition:"Geçiş durumu",signal:"Aşama {n}/4 · RSI {rsi} · 36s {dd}%",period:"{from} — {to}",tradeOf:"İşlem {n}/{all}",entry:"GİRİŞ",exit:"ÇIKIŞ",why:"GİRİŞ / ÇIKIŞ NEDENİ",noTrades:"Bu dönemde tamamlanmış işlem yok.",sent:"Mesaj özel olarak gönderildi.",sendError:"Gönderilemedi. Formu kontrol edip tekrar deneyin.",sending:"Gönderiliyor…",testError:"Hesaplama geçici olarak kullanılamıyor. Tekrar deneyin."}
};
Object.assign(copy.en,{whatIsThis:"WHAT THIS PAGE SHOWS",purposeTitle:"When the PUMP model says wait, enter or exit",purposeText:"A mathematical research assistant for PUMP/EUR. It evaluates only completed 30-minute candles and turns the four-stage strategy into a clear action scale.",modelDecision:"MODEL DECISION",prepare:"PREPARE",enter:"ENTER",fourSteps:"4-STAGE ENTRY",exitControl:"EXIT CONTROL",exitHelp:"Enter your real purchase price to see the stop, partial profit and exit zones.",purchasePrice:"Purchase price",track:"TRACK",hold:"HOLD",noPositionHint:"No position is being tracked on this device.",stopNow:"EXIT · PROTECTIVE STOP",takePartial:"TAKE 40% PROFIT",exitNow:"EXIT REMAINDER",holdPosition:"HOLD POSITION",positionMove:"Current move {p}% from your purchase price.",capitalCurve:"CAPITAL CURVE",afterTrades:"balance after each completed trade",androidControl:"VERIFIED ANDROID v2.5 CONTROL · 0.15% + 0.15%",personalizedBelow:"Your current web result below uses the selected fees and the latest rolling six-month window.",formIdentity:"Enter a name or an email.",formEmail:"Check the email address.",formMessage:"Write a message.",formConsent:"Consent is required."});
Object.assign(copy.de,{whatIsThis:"WAS DIESE SEITE ZEIGT",purposeTitle:"Wann das PUMP-Modell warten, einsteigen oder aussteigen sagt",purposeText:"Ein mathematischer Forschungsassistent für PUMP/EUR. Er bewertet nur abgeschlossene 30-Minuten-Kerzen und zeigt die Vier-Stufen-Strategie als klare Handlungsskala.",modelDecision:"MODELL-ENTSCHEIDUNG",prepare:"VORBEREITEN",enter:"EINSTIEG",fourSteps:"4-STUFEN-EINSTIEG",exitControl:"AUSSTIEGS-KONTROLLE",exitHelp:"Eigenen Kaufpreis eingeben, um Stop-, Teilgewinn- und Ausstiegszonen zu sehen.",purchasePrice:"Kaufpreis",track:"VERFOLGEN",hold:"HALTEN",noPositionHint:"Auf diesem Gerät wird keine Position verfolgt.",stopNow:"AUSSTIEG · SCHUTZSTOPP",takePartial:"40% GEWINN MITNEHMEN",exitNow:"REST AUSSTEIGEN",holdPosition:"POSITION HALTEN",positionMove:"Aktuelle Bewegung {p}% seit Ihrem Kauf.",capitalCurve:"KAPITALKURVE",afterTrades:"Kontostand nach jedem abgeschlossenen Geschäft",androidControl:"GEPRÜFTE ANDROID-v2.5-KONTROLLE · 0,15% + 0,15%",personalizedBelow:"Das aktuelle Web-Ergebnis darunter nutzt Ihre Gebühren und das neueste rollierende Sechsmonatsfenster.",formIdentity:"Name oder E-Mail eingeben.",formEmail:"E-Mail-Adresse prüfen.",formMessage:"Nachricht schreiben.",formConsent:"Zustimmung ist erforderlich."});
Object.assign(copy.tr,{whatIsThis:"BU SAYFA NE GÖSTERİR",purposeTitle:"PUMP modeli ne zaman bekle, gir veya çık der",purposeText:"PUMP/EUR için matematiksel bir araştırma yardımcısıdır. Yalnızca kapanmış 30 dakikalık mumları değerlendirir ve dört aşamalı stratejiyi net bir eylem ölçeğine dönüştürür.",modelDecision:"MODEL KARARI",prepare:"HAZIRLAN",enter:"GİR",fourSteps:"4 AŞAMALI GİRİŞ",exitControl:"ÇIKIŞ KONTROLÜ",exitHelp:"Stop, kısmi kâr ve çıkış bölgelerini görmek için gerçek alış fiyatınızı girin.",purchasePrice:"Alış fiyatı",track:"TAKİP ET",hold:"TUT",noPositionHint:"Bu cihazda takip edilen pozisyon yok.",stopNow:"ÇIK · KORUYUCU STOP",takePartial:"%40 KÂR AL",exitNow:"KALANI ÇIK",holdPosition:"POZİSYONU TUT",positionMove:"Alış fiyatınızdan güncel hareket %{p}.",capitalCurve:"SERMAYE EĞRİSİ",afterTrades:"tamamlanan her işlem sonrası bakiye",androidControl:"DOĞRULANMIŞ ANDROID v2.5 KONTROLÜ · %0,15 + %0,15",personalizedBelow:"Aşağıdaki güncel web sonucu seçilen ücretleri ve son altı aylık hareketli dönemi kullanır.",formIdentity:"İsim veya e-posta girin.",formEmail:"E-posta adresini kontrol edin.",formMessage:"Bir mesaj yazın.",formConsent:"Onay gereklidir."});
const t=key=>copy[state.lang]?.[key]||copy.en[key]||key;
const money=n=>new Intl.NumberFormat(state.lang,{style:"currency",currency:"EUR",maximumFractionDigits:Math.abs(n)<1?7:2}).format(n);
const date=(ms,time=false)=>new Intl.DateTimeFormat(state.lang,{day:"2-digit",month:"2-digit",year:"2-digit",...(time?{hour:"2-digit",minute:"2-digit"}:{})}).format(new Date(ms));
const duration=ms=>{const h=Math.round(ms/3600000);return h>=24?`${Math.floor(h/24)}d ${h%24}h`:`${h}h`};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));

function localize(){document.documentElement.lang=state.lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const value=t(el.dataset.i18n);if(value)el.textContent=value});$("languageSelect").value=state.lang;if(state.live)renderLive(state.live);if(state.result)renderResult(state.result)}
function metric(id,value,signed=false){$(id+"Value").textContent=signed?`${value>=0?"+":""}${value}`:value;$(id+"Bar").style.width=`${clamp(signed?Math.abs(value):value)}%`}

function renderLive(data){
  const sig=data.variants[state.profile]||data.variants.strict;state.live=data;
  $("pumpPrice").textContent=money(data.price);$("pumpChange").textContent=`${data.change24>=0?"+":""}${data.change24.toFixed(2)}% · 24h`;$("pumpChange").className=data.change24>0?"positive":data.change24<0?"negative":"";
  $("updatedAt").textContent=date(data.updatedAt,true);$("chartTime").textContent=date(data.candleTime,true);$("readinessValue").textContent=sig.readiness;
  const action=$("actionTag"),key=sig.blocked?"blocked":sig.readiness>=100?"enter":sig.readiness>=95?"prepare":"wait";action.className=`command ${sig.blocked?"block":sig.readiness>=100?"buy":sig.readiness>=95?"prepare":"wait"}`;action.textContent=t(key);$("signalCard").className=`signal-card ${sig.blocked?"blocked":sig.readiness>=100?"ready":""}`;
  $("entryFill").style.width=`${clamp(sig.readiness)}%`;$("entryNeedle").style.left=`${clamp(sig.readiness)}%`;$("stageCount").textContent=`${sig.stages}/4`;$("stageDots").querySelectorAll("i").forEach((dot,index)=>dot.classList.toggle("on",index<sig.stages));
  $("breathingState").textContent=t(data.breathing);$("signalReason").textContent=t("signal").replace("{n}",sig.stages).replace("{rsi}",data.rsi.toFixed(1)).replace("{dd}",data.drawdown.toFixed(1));
  metric("energy",data.energy);metric("flow",data.flow,true);metric("confidence",data.agreement);metric("late",sig.late);drawPriceChart($("liveCanvas"),data.chart);renderPosition();
}

function renderPosition(){if(!state.live)return;const input=$("positionEntry"),entry=state.entryPrice,price=state.live.price;if(entry>0&&!input.matches(":focus"))input.value=entry.toFixed(8);if(!entry){$("exitAction").textContent=t("noPosition");$("positionPnl").textContent="—";$("exitNeedle").style.left="28%";$("exitReason").textContent=t("noPositionHint");return}const pnl=(price/entry-1)*100,scale=clamp((pnl+4.4)/18.4*100),action=pnl<=-4.4?"stopNow":pnl>=14?"exitNow":pnl>=7?"takePartial":"holdPosition";$("exitAction").textContent=t(action);$("exitAction").className=pnl<=-4.4||pnl>=14?"danger":pnl>=7?"profit":"";$("positionPnl").textContent=`${pnl>=0?"+":""}${pnl.toFixed(2)}%`;$("positionPnl").className=pnl>=0?"positive":"negative";$("exitNeedle").style.left=`${scale}%`;$("exitReason").textContent=t("positionMove").replace("{p}",`${pnl>=0?"+":""}${pnl.toFixed(2)}`)}

async function refreshLive(){try{const response=await fetch("/market-snapshot",{cache:"no-store"});if(!response.ok)throw Error(response.status);renderLive(await response.json());$("connectionBadge").className="live-badge";$("connectionBadge").querySelector("span").textContent=t("readyData")}catch(error){console.error(error);$("connectionBadge").className="live-badge error";$("connectionBadge").querySelector("span").textContent=t("offline")}}

function readSettings(){const value=(id,fallback,max)=>clamp(Number.parseFloat($(id).value)||fallback,id==="startCapital"?10:0,max);return{capital:value("startCapital",1000,1e7),buyFee:value("entryFee",.25,25)/100,sellFee:value("exitFee",.25,25)/100,slippage:value("slippage",.05,25)/100}}
function saveSettings(){for(const id of ["startCapital","entryFee","exitFee","slippage"])localStorage.setItem("pp_"+id,$(id).value)}
function loadSettings(){if(!localStorage.getItem("pp_defaults_v4")){localStorage.setItem("pp_entryFee","0.25");localStorage.setItem("pp_exitFee","0.25");localStorage.setItem("pp_defaults_v4","1")}for(const id of ["startCapital","entryFee","exitFee","slippage"]){const value=localStorage.getItem("pp_"+id);if(value!==null)$(id).value=value}}

async function runBacktest(){saveSettings();$("testResults").classList.add("hidden");$("testLoading").classList.remove("hidden");$("runBacktest").disabled=true;try{const response=await fetch("/backtest-result",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...readSettings(),profile:state.profile})});if(!response.ok)throw Error(await response.text());state.result=await response.json();renderResult(state.result);$("testResults").classList.remove("hidden")}catch(error){console.error(error);alert(t("testError"))}finally{$("testLoading").classList.add("hidden");$("runBacktest").disabled=false}}

function renderResult(result){const positive=result.profit>=0;$("resultProfile").textContent=`PUMP/EUR · ${t(result.profile==="active"?"active":"strict")}`;$("resultPercent").textContent=`${result.profitPct>=0?"+":""}${result.profitPct.toFixed(2)}%`;$("resultPercent").style.color=positive?"var(--green)":"var(--rose)";$("resultMoney").textContent=`${result.profit>=0?"+":""}${money(result.profit)}`;$("resultMoney").style.color=positive?"var(--green)":"var(--rose)";$("balancePath").textContent=`${money(result.settings.capital)} → ${money(result.equity)}`;$("tradeCount").textContent=result.rounds;$("winRate").textContent=`${result.winRate.toFixed(0)}%`;$("drawdown").textContent=`${result.maxDd.toFixed(2)}%`;$("feeTotal").textContent=money(result.totalFees);$("testPeriod").textContent=t("period").replace("{from}",date(result.from)).replace("{to}",date(result.to));$("tradeSummary").textContent=`${result.rounds} · ${result.stops} stops`;drawEquityChart($("testCanvas"),result.equityCurve||[[result.from,result.settings.capital],[result.to,result.equity]]);
  const list=$("tradeList");list.innerHTML="";if(!result.connections.length){list.innerHTML=`<p>${esc(t("noTrades"))}</p>`;return}result.connections.slice().reverse().forEach((trade,index)=>{const number=result.connections.length-index,card=document.createElement("article");card.className=`trade-card ${trade.pnl<0?"negative":""}`;card.innerHTML=`<header><h3>${esc(t("tradeOf").replace("{n}",number).replace("{all}",result.connections.length))}</h3><strong>${trade.pct>=0?"+":""}${trade.pct.toFixed(2)}%</strong></header><p>${trade.pnl>=0?"+":""}${esc(money(trade.pnl))} · ${duration(trade.duration)}<br>${esc(t("entry"))} ${date(trade.entry.time,true)} · ${esc(money(trade.entry.price))}<br>${esc(t("exit"))} ${date(trade.exit.time,true)} · ${esc(money(trade.exit.price))}</p><details><summary>${esc(t("why"))}</summary><p>${esc(trade.entry.reason)}<br>${esc(trade.exit.reason)}${trade.partial?`<br>${esc(trade.partial)}`:""}</p></details>`;list.append(card)});
}

function canvasBase(canvas){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),width=Math.max(280,rect.width),height=canvas.clientHeight||200;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);ctx.clearRect(0,0,width,height);ctx.lineJoin="round";ctx.lineCap="round";return{ctx,width,height}}
function drawPriceChart(canvas,all){if(!all?.length)return;const points=all.slice(-96),{ctx,width,height}=canvasBase(canvas),values=points.flatMap(p=>[p[1],p[2]]).filter(Number.isFinite),low=Math.min(...values),high=Math.max(...values),pad=(high-low)*.12||1,x=i=>10+i/Math.max(1,points.length-1)*(width-20),y=v=>height-14-(v-(low-pad))/(high-low+2*pad)*(height-28);ctx.strokeStyle="rgba(135,151,181,.13)";ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(8,height*i/4);ctx.lineTo(width-8,height*i/4);ctx.stroke()}const line=(key,color,size)=>{ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(x(i),y(p[key])):ctx.moveTo(x(i),y(p[key])));ctx.strokeStyle=color;ctx.lineWidth=size;ctx.stroke()};line(2,"rgba(155,123,255,.65)",1.2);line(1,"#2dd4ff",2.4)}
function drawEquityChart(canvas,points){if(!points?.length)return;const {ctx,width,height}=canvasBase(canvas),values=points.map(p=>p[1]),low=Math.min(...values),high=Math.max(...values),pad=Math.max((high-low)*.18,1),x=i=>14+i/Math.max(1,points.length-1)*(width-28),y=v=>height-24-(v-(low-pad))/(high-low+2*pad)*(height-42);ctx.strokeStyle="rgba(135,151,181,.14)";ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(12,height*i/4);ctx.lineTo(width-12,height*i/4);ctx.stroke()}const grad=ctx.createLinearGradient(0,0,0,height);grad.addColorStop(0,"rgba(66,229,161,.28)");grad.addColorStop(1,"rgba(45,212,255,0)");ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(x(i),y(p[1])):ctx.moveTo(x(i),y(p[1])));ctx.lineTo(x(points.length-1),height-16);ctx.lineTo(x(0),height-16);ctx.closePath();ctx.fillStyle=grad;ctx.fill();ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(x(i),y(p[1])):ctx.moveTo(x(i),y(p[1])));ctx.strokeStyle=values.at(-1)>=values[0]?"#42e5a1":"#ff557d";ctx.lineWidth=3;ctx.stroke();points.forEach((p,i)=>{ctx.beginPath();ctx.arc(x(i),y(p[1]),i===points.length-1?4:2.4,0,Math.PI*2);ctx.fillStyle=i===points.length-1?"#fff":"#2dd4ff";ctx.fill()});$("chartRange").textContent=`${money(low)} — ${money(high)}`}

function showTab(tab){state.tab=tab;document.querySelectorAll(".view").forEach(view=>view.classList.toggle("active",view.dataset.view===tab));document.querySelectorAll(".dock button").forEach(button=>button.classList.toggle("active",button.dataset.tab===tab));scrollTo({top:0,behavior:"smooth"});if(tab==="test"){if(state.result){renderResult(state.result);$("testResults").classList.remove("hidden")}else runBacktest()}}
document.querySelectorAll("[data-tab]").forEach(button=>button.addEventListener("click",()=>showTab(button.dataset.tab)));
$("languageSelect").addEventListener("change",event=>{state.lang=event.target.value;localStorage.setItem("pp_lang",state.lang);localize()});
$("profileSwitch").addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;state.profile=button.dataset.value;localStorage.setItem("pp_profile",state.profile);$("profileSwitch").querySelectorAll("button").forEach(item=>item.classList.toggle("active",item===button));if(state.live)renderLive(state.live);if(state.result)runBacktest()});
document.querySelectorAll(".presets button").forEach(button=>button.addEventListener("click",()=>{$("entryFee").value=button.dataset.fees;$("exitFee").value=button.dataset.fees;document.querySelectorAll(".presets button").forEach(item=>item.classList.toggle("active",item===button))}));
$("runBacktest").addEventListener("click",runBacktest);
$("trackPosition").addEventListener("click",()=>{const value=Number.parseFloat($("positionEntry").value);state.entryPrice=Number.isFinite(value)&&value>0?value:0;if(state.entryPrice)localStorage.setItem("pp_entry_price",String(state.entryPrice));else localStorage.removeItem("pp_entry_price");renderPosition()});
$("contactForm").addEventListener("submit",async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),name=String(data.get("name")||"").trim(),email=String(data.get("email")||"").trim(),message=String(data.get("message")||"").trim(),consent=form.querySelector(".consent input").checked,status=$("contactStatus"),button=form.querySelector("button[type=submit]");status.className="form-status";let error="";if(!name&&!email)error=t("formIdentity");else if(email&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))error=t("formEmail");else if(!message)error=t("formMessage");else if(!consent)error=t("formConsent");if(error){status.className="form-status error";status.textContent=error;return}button.disabled=true;status.textContent=t("sending");try{const response=await fetch("/contact-message",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,email,message,website:data.get("website"),language:state.lang})});if(!response.ok)throw Error(await response.text());form.reset();status.className="form-status success";status.textContent=t("sent")}catch(error){console.error(error);status.className="form-status error";status.textContent=t("sendError")}finally{button.disabled=false}});
window.addEventListener("resize",()=>{if(state.live)drawPriceChart($("liveCanvas"),state.live.chart);if(state.result)drawEquityChart($("testCanvas"),state.result.equityCurve||[])});
loadSettings();$("languageSelect").value=state.lang;$("profileSwitch").querySelectorAll("button").forEach(button=>button.classList.toggle("active",button.dataset.value===state.profile));if(state.entryPrice)$("positionEntry").value=state.entryPrice.toFixed(8);localize();if(state.live)renderLive(state.live);refreshLive();setInterval(refreshLive,120000);
