const AUTHOR_EMAIL_HASH = "164c8bd3264723dc5a617b04e245335fe528a1b0dc52b58a3f2ca2e9be2f1977";
const MESSAGE_SCHEMA = "CREATE TABLE IF NOT EXISTS pump_pulse_messages (id TEXT PRIMARY KEY, created_at TEXT NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, message TEXT NOT NULL, language TEXT NOT NULL, is_read INTEGER NOT NULL DEFAULT 0)";
const CACHE_SCHEMA = "CREATE TABLE IF NOT EXISTS pump_pulse_cache (key TEXT PRIMARY KEY, updated_at INTEGER NOT NULL, payload TEXT NOT NULL)";
const VISIT_SCHEMA = "CREATE TABLE IF NOT EXISTS pump_pulse_visits (id INTEGER PRIMARY KEY, total INTEGER NOT NULL DEFAULT 0)";
const securityHeaders = {"Referrer-Policy":"strict-origin-when-cross-origin","X-Content-Type-Options":"nosniff","X-Frame-Options":"SAMEORIGIN","Permissions-Policy":"camera=(), microphone=(), geolocation=()"};
const encoder = new TextEncoder();
const SITE_URL="https://pump-pulse-market.serano.chatgpt.site";
const HTML_PATHS=new Set(["/","/index.html","/de","/de/","/tr","/tr/"]);
const SEO_LOCALES={
  en:{lang:"en",locale:"en_US",canonical:SITE_URL+"/",title:"PUMP Pulse — PUMP Coin Entry &amp; Exit Signals, Live EUR Chart and Backtest",description:"Track the live PUMP coin price in EUR, view 30-minute entry and exit readiness, follow a manual position and test the PUMP strategy over six months. Research tool only.",keywords:"PUMP coin price, PUMP/EUR chart, PUMP token trading signals, PUMP entry signal, PUMP exit signal, PUMP backtest, pump.fun coin analysis, crypto PUMP strategy, buy sell indicator, 30 minute crypto strategy",purpose:"PUMP Coin entry and exit signals with a live EUR chart",purposeText:"Follow the live PUMP/EUR price, 30-minute buy and sell readiness, manual percentage position tracking and a six-month strategy backtest."},
  de:{lang:"de",locale:"de_DE",canonical:SITE_URL+"/de",title:"PUMP Pulse — PUMP Coin Einstiegs- &amp; Ausstiegssignale, Live-Euro-Chart und Rücktest",description:"Live PUMP-Kurs in Euro, 30-Minuten-Einstiegs- und Ausstiegssignale, prozentuale Positionsverfolgung und sechsmonatiger PUMP-Strategie-Rücktest.",keywords:"PUMP Kurs Euro, PUMP Coin Chart, PUMP Einstiegssignal, PUMP Ausstiegssignal, PUMP Strategie, PUMP Rücktest, PUMP kaufen verkaufen, Kryptowährung Handelssignal, PUMP Preis heute, Krypto Einstieg Ausstieg",purpose:"PUMP-Coin Einstiegs- und Ausstiegssignale mit Live-Euro-Chart",purposeText:"Live-PUMP/EUR-Kurs, 30-Minuten-Kauf- und Verkaufssignale, prozentuale Positionsverfolgung und sechsmonatigen Strategie-Rücktest ansehen."},
  tr:{lang:"tr",locale:"tr_TR",canonical:SITE_URL+"/tr",title:"PUMP Pulse — PUMP Coin Alım Satım Sinyalleri, Canlı EUR Grafik ve Strateji Testi",description:"Canlı PUMP coin fiyatını Euro olarak izleyin; 30 dakikalık alım-satım hazırlığını, yüzde pozisyon takibini ve altı aylık strateji testini görün.",keywords:"PUMP coin fiyatı, PUMP EUR grafik, PUMP alım sinyali, PUMP satış sinyali, PUMP stratejisi, PUMP geriye dönük test, kripto işlem sinyali, PUMP al sat, PUMP fiyat bugün, kripto giriş çıkış",purpose:"Canlı EUR grafiği ile PUMP coin alım ve satım sinyalleri",purposeText:"Canlı PUMP/EUR fiyatını, 30 dakikalık alım-satım hazırlığını, yüzde pozisyon takibini ve altı aylık strateji testini görüntüleyin."}
};

function localizedHtml(source,pathname){
  const lang=pathname.startsWith("/de")?"de":pathname.startsWith("/tr")?"tr":"en",seo=SEO_LOCALES[lang];
  return source
    .replace(/<html lang="[^"]+"/,`<html lang="${seo.lang}"`)
    .replace(/<title>[^<]*<\/title>/,`<title>${seo.title}</title>`)
    .replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${seo.description}">`)
    .replace(/<meta name="keywords" content="[^"]*">/,`<meta name="keywords" content="${seo.keywords}">`)
    .replace(/<link rel="canonical" href="[^"]*">/,`<link rel="canonical" href="${seo.canonical}">`)
    .replace(/<meta property="og:locale" content="[^"]*">/,`<meta property="og:locale" content="${seo.locale}">`)
    .replace(/<meta property="og:url" content="[^"]*">/,`<meta property="og:url" content="${seo.canonical}">`)
    .replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${seo.title}">`)
    .replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${seo.description}">`)
    .replace(/<meta name="twitter:title" content="[^"]*">/,`<meta name="twitter:title" content="${seo.title}">`)
    .replace(/<meta name="twitter:description" content="[^"]*">/,`<meta name="twitter:description" content="${seo.description}">`)
    .replace(/(<h1 data-i18n="purpose">)[^<]*(<\/h1>)/,`$1${seo.purpose}$2`)
    .replace(/(<p data-i18n="purposeText">)[^<]*(<\/p>)/,`$1${seo.purposeText}$2`);
}

function clean(value,max){return String(value||"").trim().slice(0,max)}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]))}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{...securityHeaders,"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
async function sha256(value){const digest=await crypto.subtle.digest("SHA-256",encoder.encode(value));return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("")}
function cookie(request,name){const source=request.headers.get("cookie")||"";for(const part of source.split(";")){const [key,...rest]=part.trim().split("=");if(key===name)return decodeURIComponent(rest.join("="))}return""}
async function isAuthor(request,env){const email=String(request.headers.get("oai-authenticated-user-email")||"").trim().toLowerCase();if(email&&await sha256(email)===AUTHOR_EMAIL_HASH)return true;const access=cookie(request,"pump_pulse_owner");return !!env?.AUTHOR_ACCESS_TOKEN&&!!access&&await sha256(access)===await sha256(env.AUTHOR_ACCESS_TOKEN)}
async function authorAccess(request,env){const url=new URL(request.url),key=url.searchParams.get("key")||"";if(!env?.AUTHOR_ACCESS_TOKEN||!key||await sha256(key)!==await sha256(env.AUTHOR_ACCESS_TOKEN))return new Response("Private link is invalid",{status:403,headers:securityHeaders});return new Response(null,{status:302,headers:{...securityHeaders,"location":"/private-author-inbox","cache-control":"no-store","referrer-policy":"no-referrer","set-cookie":`pump_pulse_owner=${encodeURIComponent(key)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=31536000`}})}
async function ensureDb(env){if(!env?.DB)throw new Error("Database unavailable");await env.DB.prepare(MESSAGE_SCHEMA).run();await env.DB.prepare(CACHE_SCHEMA).run();await env.DB.prepare(VISIT_SCHEMA).run()}
async function cacheGet(env,key){await ensureDb(env);const row=await env.DB.prepare("SELECT updated_at, payload FROM pump_pulse_cache WHERE key = ?").bind(key).first();if(!row)return null;try{return{updatedAt:Number(row.updated_at),data:JSON.parse(row.payload)}}catch{return null}}
async function cachePut(env,key,data){await ensureDb(env);const now=Date.now();await env.DB.prepare("INSERT INTO pump_pulse_cache (key, updated_at, payload) VALUES (?, ?, ?) ON CONFLICT(key) DO UPDATE SET updated_at=excluded.updated_at, payload=excluded.payload").bind(key,now,JSON.stringify(data)).run();return now}

function expand(x){return{openTime:x[0],open:x[1],high:x[2],low:x[3],close:x[4],volume:x[5],closeTime:x[6],taker:x[7]}}
function expandPrice(x){return{openTime:x[0]-1799999,open:x[1],high:x[1],low:x[1],close:x[1],volume:0,closeTime:x[0],taker:0}}
function expandContext(x){return{openTime:x[0]-1799999,open:x[1],high:x[1],low:x[1],close:x[1],volume:x[2],closeTime:x[0],taker:x[3]}}
let seedMemo=null;
function seedHistory(){if(seedMemo)return seedMemo;seedMemo={pump:synthEur(HISTORY_SEED.pump.map(expand),HISTORY_SEED.eur.map(expand)),btc:HISTORY_SEED.btc.map(expandPrice),eth:(HISTORY_SEED.eth||[]).map(expandContext),sol:(HISTORY_SEED.sol||[]).map(expandContext),futures:(HISTORY_SEED.futures||[]).map(expandContext),premium:(HISTORY_SEED.premium||[]).map(expandPrice),funding:(HISTORY_SEED.funding||[]).map(x=>({time:x[0],rate:x[1]}))};return seedMemo}
async function recentCoinGeckoCandles(){const response=await fetch("https://api.coingecko.com/api/v3/coins/pump-fun/market_chart?vs_currency=eur&days=1",{headers:{accept:"application/json","user-agent":"PUMP-Pulse/1.0"}});if(!response.ok)throw new Error("CoinGecko response "+response.status);const body=await response.json(),prices=body.prices||[],last=prices.at(-1)||[],volumes=body.total_volumes||[],volumeAt=new Map(volumes.map(x=>[x[0],x[1]])),groups=new Map();for(const point of prices){const time=point[0],price=Number(point[1]),bucket=Math.floor(time/1800000)*1800000;if(!Number.isFinite(price))continue;const group=groups.get(bucket)||{openTime:bucket,open:price,high:price,low:price,close:price,volume:0,closeTime:bucket+1799999,taker:0};group.high=Math.max(group.high,price);group.low=Math.min(group.low,price);group.close=price;group.volume=Math.max(group.volume,Number(volumeAt.get(time))||0);groups.set(bucket,group)}const now=Date.now(),candles=[...groups.values()].filter(c=>c.closeTime<now).map(c=>({...c,volume:Math.max(1,c.volume),taker:Math.max(1,c.volume)*(c.close>=c.open ? .58 : .42)})).sort((a,b)=>a.closeTime-b.closeTime);return{candles,currentPrice:Number(last[1])||candles.at(-1)?.close,currentTime:Number(last[0])||candles.at(-1)?.closeTime}}
async function coinbaseProduct(product,quoteToEur=1){const headers={accept:"application/json","user-agent":"PUMP-Pulse/1.0"},[candlesResponse,tickerResponse]=await Promise.all([fetch(`https://api.exchange.coinbase.com/products/${product}/candles?granularity=900`,{headers}),fetch(`https://api.exchange.coinbase.com/products/${product}/ticker`,{headers})]);if(!candlesResponse.ok||!tickerResponse.ok)throw new Error("Coinbase "+product+" response "+candlesResponse.status+"/"+tickerResponse.status);const rows=await candlesResponse.json(),ticker=await tickerResponse.json(),groups=new Map();for(const row of rows){const time=Number(row[0])*1000,low=Number(row[1])*quoteToEur,high=Number(row[2])*quoteToEur,open=Number(row[3])*quoteToEur,close=Number(row[4])*quoteToEur,volume=Number(row[5]),bucket=Math.floor(time/1800000)*1800000;if(![time,low,high,open,close].every(Number.isFinite))continue;const group=groups.get(bucket)||{openTime:bucket,open,high,low,close,volume:0,closeTime:bucket+1799999,taker:0};if(time<group.openTime+900000)group.open=open;group.high=Math.max(group.high,high);group.low=Math.min(group.low,low);if(time>=group.openTime+900000)group.close=close;group.volume+=Number.isFinite(volume)?volume:0;groups.set(bucket,group)}const now=Date.now(),candles=[...groups.values()].filter(c=>c.closeTime<now).map(c=>({...c,volume:Math.max(1,c.volume),taker:Math.max(1,c.volume)*(c.close>=c.open ? .58 : .42)})).sort((a,b)=>a.closeTime-b.closeTime),currentPrice=Number(ticker.price)*quoteToEur||candles.at(-1)?.close;return{candles,currentPrice,currentTime:Date.now()}}
async function recentCoinbaseCandles(){try{return await coinbaseProduct("PUMP-EUR")}catch{const response=await fetch("https://api.exchange.coinbase.com/products/USDC-EUR/ticker",{headers:{accept:"application/json","user-agent":"PUMP-Pulse/1.0"}});if(!response.ok)throw new Error("Coinbase USDC-EUR response "+response.status);const eurPerUsd=Number((await response.json()).price);if(!Number.isFinite(eurPerUsd)||eurPerUsd<=0)throw new Error("Coinbase USDC-EUR invalid");return coinbaseProduct("PUMP-USD",eurPerUsd)}}
async function recentPumpCandles(){try{return await recentCoinGeckoCandles()}catch(first){console.warn("Live provider fallback",String(first?.message||first));try{return await recentCoinbaseCandles()}catch(second){console.warn("Live providers unavailable",String(second?.message||second));throw second}}}
function alignedSeries(name,pump){const source=seedHistory()[name]||[],byTime=new Map(source.map(c=>[c.closeTime,c])),fallback=source.at(-1);return pump.map(c=>byTime.get(c.closeTime)||fallback&&{...fallback,openTime:c.openTime,closeTime:c.closeTime}).filter(Boolean)}
function fullContext(pump){const seed=seedHistory();return{pump,btc:alignedSeries("btc",pump),eth:alignedSeries("eth",pump),sol:alignedSeries("sol",pump),futures:alignedSeries("futures",pump),premium:alignedSeries("premium",pump),funding:seed.funding}}
function seedLive(){const base=seedHistory().pump.slice(-1000),data=liveSnapshot(fullContext(base));return{...data,updatedAt:data.candleTime,livePrice:data.price,livePriceTime:data.candleTime,source:"cached"}}
async function refreshLive(env){const base=seedHistory().pump.slice(-1000),recentData=await recentPumpCandles(),recent=recentData.candles,cut=recent[0]?.closeTime||Infinity,merged=[...base.filter(c=>c.closeTime<cut),...recent],unique=[...new Map(merged.map(c=>[c.closeTime,c])).values()].sort((a,b)=>a.closeTime-b.closeTime).slice(-1000),data=liveSnapshot(fullContext(unique)),lastEma=data.chart.at(-1)?.[2]||recentData.currentPrice;data.price=recentData.currentPrice;data.livePrice=recentData.currentPrice;data.livePriceTime=recentData.currentTime;data.updatedAt=Date.now();data.source="live";if(data.chart.at(-1)?.[0]!==recentData.currentTime)data.chart.push([recentData.currentTime,recentData.currentPrice,lastEma]);await cachePut(env,"live-v3",data);return data}
async function getLive(env,ctx,fresh=false){const cached=await cacheGet(env,"live-v3");if(cached){if(Date.now()-cached.updatedAt>25000){if(fresh){try{return await refreshLive(env)}catch(error){console.warn("Serving cached market",String(error?.message||error));return{...cached.data,source:"cached",providerError:String(error?.message||error)}}}if(ctx?.waitUntil)ctx.waitUntil(refreshLive(env).catch(error=>console.warn("Background market refresh failed",String(error?.message||error))))}return cached.data}const data=seedLive();await cachePut(env,"live-v3",data);if(ctx?.waitUntil)ctx.waitUntil(refreshLive(env).catch(error=>console.warn("Initial market refresh failed",String(error?.message||error))));return data}
async function getHistory(){return seedHistory()}

async function defaultBacktest(env){const key="backtest-default-v4:"+HISTORY_SEED.generatedAt,cached=await cacheGet(env,key);if(cached)return cached.data;const history=seedHistory(),result=runStrategy(history,{capital:1000,buyFee:.0025,sellFee:.0025,slippage:.0005,startTime:history.pump[236].openTime,endTime:history.pump.at(-1).closeTime},"strict");await cachePut(env,key,result);return result}
async function backtest(request,env,ctx){let body;try{body=await request.json()}catch{return new Response("Invalid request",{status:400})}const history=await getHistory(env,ctx),availableFrom=history.pump[236]?.openTime||history.pump[0].openTime,availableTo=history.pump.at(-1).closeTime,startTime=clamp(Number(body.startTime)||availableFrom,availableFrom,availableTo),endTime=clamp(Number(body.endTime)||availableTo,startTime,availableTo),settings={capital:1000,buyFee:clamp(Number(body.buyFee)||.0025,0,.25),sellFee:clamp(Number(body.sellFee)||.0025,0,.25),slippage:clamp(Number(body.slippage)||.0005,0,.25),startTime,endTime},profile=body.profile==="active"?"active":"strict";return json(runStrategy(history,settings,profile))}

async function visitCounter(request,env){await ensureDb(env);const seen=!!cookie(request,"pump_pulse_visitor"),shouldCount=request.method==="POST"&&!seen;if(shouldCount)await env.DB.prepare("INSERT INTO pump_pulse_visits (id, total) VALUES (1, 1) ON CONFLICT(id) DO UPDATE SET total=total+1").run();const row=await env.DB.prepare("SELECT total FROM pump_pulse_visits WHERE id = 1").first(),headers={...securityHeaders,"content-type":"application/json; charset=utf-8","cache-control":"no-store"};if(shouldCount)headers["set-cookie"]=`pump_pulse_visitor=${crypto.randomUUID()}; Path=/; Secure; SameSite=Lax; Max-Age=31536000`;return new Response(JSON.stringify({total:Number(row?.total)||0}),{headers})}

async function contact(request,env){await ensureDb(env);let body;try{body=await request.json()}catch{return new Response("Invalid request",{status:400})}if(clean(body.website,200))return json({ok:true});const name=clean(body.name,80),email=clean(body.email,160),message=clean(body.message,3000),language=clean(body.language,5)||"en";if((!name&&!email)||(email&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))||!message)return new Response("Please check the form",{status:400});const id=crypto.randomUUID(),createdAt=new Date().toISOString();await env.DB.prepare("INSERT INTO pump_pulse_messages (id, created_at, name, email, message, language, is_read) VALUES (?, ?, ?, ?, ?, ?, 0)").bind(id,createdAt,name,email,message,language).run();if(env.CONTACT_WEBHOOK_URL){try{await fetch(env.CONTACT_WEBHOOK_URL,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"pump_pulse_contact",id,createdAt,name,email,language})})}catch{}}return json({ok:true},201)}

async function inbox(request,env){if(!await isAuthor(request,env))return new Response("<!doctype html><html><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><meta name=robots content=noindex><title>Private</title><style>body{margin:0;background:#050816;color:#f3f6ff;font:16px system-ui;display:grid;place-content:center;min-height:100vh;text-align:center}main{padding:24px}a{color:#2dd4ff}</style></head><body><main><h1>🔒 Author inbox</h1><p>This inbox opens only through the owner's private link.</p><a href='/'>Back to PUMP Pulse</a></main></body></html>",{status:403,headers:{...securityHeaders,"content-type":"text/html; charset=utf-8","cache-control":"no-store"}});await ensureDb(env);const result=await env.DB.prepare("SELECT id, created_at, name, email, message, language, is_read FROM pump_pulse_messages ORDER BY created_at DESC LIMIT 200").all();await env.DB.prepare("UPDATE pump_pulse_messages SET is_read=1 WHERE is_read=0").run();const rows=(result.results||[]).map(row=>{const who=escapeHtml(row.name||"Anonymous"),mail=row.email?"<a href='mailto:"+encodeURIComponent(row.email)+"'>"+escapeHtml(row.email)+"</a>":"<span>No email</span>";return"<article class='"+(row.is_read?"":"new")+"'><header><b>"+who+"</b>"+mail+"</header><small>"+escapeHtml(new Date(row.created_at).toLocaleString("de-DE"))+" · "+escapeHtml(row.language)+"</small><p>"+escapeHtml(row.message).replace(/\n/g,"<br>")+"</p></article>"}).join("")||"<p>No messages yet.</p>";const page="<!doctype html><html><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1'><meta name=robots content=noindex><title>PUMP Pulse · Inbox</title><style>body{margin:0;background:#050816;color:#f3f6ff;font:15px system-ui}main{width:min(760px,calc(100% - 24px));margin:auto;padding:20px 0}nav,header{display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap}a{color:#2dd4ff}article{margin-top:10px;padding:14px;border:1px solid #202b43;border-radius:14px;background:#0b1020}article.new{border-color:#2dd4ff}small{color:#8793aa}p{line-height:1.55}</style></head><body><main><nav><h1>🔒 Author inbox</h1><a href='/'>PUMP Pulse</a></nav>"+rows+"</main></body></html>";return new Response(page,{headers:{...securityHeaders,"content-type":"text/html; charset=utf-8","cache-control":"no-store"}})}

export default{async fetch(request,env,ctx){const url=new URL(request.url);try{if(url.pathname==="/market-snapshot"&&request.method==="GET")return json(await getLive(env,ctx,true));if(url.pathname==="/visit-counter"&&(request.method==="GET"||request.method==="POST"))return visitCounter(request,env);if(url.pathname==="/backtest-result"&&request.method==="POST")return backtest(request,env,ctx);if(url.pathname==="/contact-message"&&request.method==="POST")return contact(request,env);if(url.pathname==="/author-access"&&request.method==="GET")return authorAccess(request,env);if(url.pathname==="/private-author-inbox"&&request.method==="GET")return inbox(request,env);const asset=assets.get(url.pathname);if(!asset)return new Response("Not found",{status:404,headers:securityHeaders});let body=asset.body;if(HTML_PATHS.has(url.pathname)){body=localizedHtml(body,url.pathname);try{const[snapshot,test]=await Promise.all([getLive(env,ctx),defaultBacktest(env)]),safe=JSON.stringify({live:snapshot,backtest:test}).replace(/</g,"\\u003c");body=body.replace("</head>","<script id='pump-initial-data' type='application/json'>"+safe+"</script></head>")}catch{}return new Response(body,{headers:{...securityHeaders,"content-type":asset.type,"cache-control":"no-store"}})}return new Response(body,{headers:{...securityHeaders,"content-type":asset.type,"cache-control":"public, max-age=31536000, immutable"}})}catch(error){return json({error:"Service temporarily unavailable",detail:String(error?.message||error)},503)}}};
