#!/usr/bin/env node
const fs=require('fs');
const API='https://data-api.binance.vision/api/v3/klines';
const TEST_START=Date.parse('2026-02-01T00:00:00Z');
const TEST_END=Date.parse('2026-03-01T00:00:00Z');
const FETCH_START=TEST_START-10*86400000;
const FETCH_END=TEST_END+8*86400000;
const FEE=.0021, SLIP=.0008;
const LIMIT_DROP=.025, TTL_MS=60*60000, TP_NET=.05, STOP_NET=-.15, BE_TRIGGER_NET=.03;
const MAX_HOLD_MS=7*86400000, MIN_ENTRY_GAP_MS=18*3600000;
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const net=(e,x)=>x*(1-FEE)/(e*(1+FEE))-1;
const priceForNet=(e,n)=>e*(1+n)*(1+FEE)/(1-FEE);
async function fetchK(symbol,interval,start,end){const out=[];let cursor=start;while(cursor<end){const u=`${API}?symbol=${symbol}&interval=${interval}&startTime=${cursor}&endTime=${end-1}&limit=1000`;const r=await fetch(u);if(!r.ok)throw Error(`${symbol} ${interval} ${r.status}`);const rows=await r.json();if(!rows.length)break;out.push(...rows);const next=+rows.at(-1)[0]+(interval==='1m'?60000:1800000);if(next<=cursor)break;cursor=next;}return out.map(x=>({openTime:+x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5],closeTime:+x[6],taker:+x[9]}));}
function ema(values,period){if(!values.length)return[];const k=2/(period+1),out=[];let value=values[0];values.forEach((next,index)=>{value=index?next*k+value*(1-k):next;out.push(value)});return out}
function rsi(values,period=14){const out=Array(values.length).fill(null);if(values.length<=period)return out;let gain=0,loss=0;for(let i=1;i<=period;i++){const d=values[i]-values[i-1];gain+=Math.max(d,0);loss+=Math.max(-d,0)}gain/=period;loss/=period;out[period]=loss?100-100/(1+gain/loss):100;for(let i=period+1;i<values.length;i++){const d=values[i]-values[i-1];gain=(gain*(period-1)+Math.max(d,0))/period;loss=(loss*(period-1)+Math.max(-d,0))/period;out[i]=loss?100-100/(1+gain/loss):100}return out}
function candleReturn(c,i,bars){return i>=bars&&c[i-bars].close?c[i].close/c[i-bars].close-1:0}
function indicators(primary,btc,solContext){const closes=primary.map(x=>x.close),e20=ema(closes,20),e200=ema(closes,200),rs=rsi(closes),btcE200=ema(btc.map(x=>x.close),200),btcE50=ema(btc.map(x=>x.close),50),btcBy=new Map(btc.map((x,i)=>[x.closeTime,{...x,i}])),solBy=new Map(solContext.map(x=>[x.closeTime,x]));const volumeRatio=[],drawdown=[],shockCount=[],breakout=[],spotFlow=[],atr=[];for(let i=0;i<primary.length;i++){const w=primary.slice(Math.max(0,i-19),i+1).map(x=>x.volume).sort((a,b)=>a-b),med=w.length>=20?(w[9]+w[10])/2:w.reduce((a,b)=>a+b,0)/Math.max(1,w.length);volumeRatio[i]=med?primary[i].volume/med:0;const high=Math.max(...primary.slice(Math.max(0,i-71),i+1).map(x=>x.high));drawdown[i]=primary[i].close/high-1;shockCount[i]=Array.from({length:Math.min(36,i+1)},(_,k)=>candleReturn(primary,i-k,1)).filter(x=>x<=-.02).length;breakout[i]=i>=6&&primary[i].close>=Math.max(...primary.slice(i-6,i).map(x=>x.high));const flow=primary.slice(Math.max(0,i-2),i+1);spotFlow[i]=flow.length===3?flow.reduce((a,x)=>a+(x.volume?2*x.taker/x.volume-1:0),0)/3:null;const ranges=[];for(let j=Math.max(1,i-13);j<=i;j++)ranges.push(Math.max(primary[j].high-primary[j].low,Math.abs(primary[j].high-primary[j-1].close),Math.abs(primary[j].low-primary[j-1].close)));atr[i]=ranges.length===14?ranges.reduce((a,b)=>a+b,0)/14/primary[i].close:null}return{e20,e200,rs,volumeRatio,drawdown,shockCount,breakout,spotFlow,atr,btcBy,solBy,btcE200,btcE50,btcAbove(i){const b=btcBy.get(primary[i].closeTime);return!!b&&b.close>btcE200[b.i]},btcSlope(i){const b=btcBy.get(primary[i].closeTime);return!!b&&b.i>=6&&btcE50[b.i]>btcE50[b.i-6]},market(i){if(i<6)return null;const b1=btcBy.get(primary[i].closeTime),b0=btcBy.get(primary[i-6].closeTime),s1=solBy.get(primary[i].closeTime),s0=solBy.get(primary[i-6].closeTime);return b1&&b0&&s1&&s0?((b1.close/b0.close-1)+(s1.close/s0.close-1))/2:null}}}
function lateRisk(p,ind,i){if(i<48)return 0;const w=p.slice(i-47,i+1),lo=Math.min(...w.map(x=>x.low)),hi=Math.max(...w.map(x=>x.high)),location=(p[i].close-lo)/Math.max(1e-12,hi-lo),rr=ind.rs[i]||50;return Math.round(clamp(100*(.30*clamp((location-.5)/.5,0,1)+.20*clamp((rr-50)/18,0,1)+.20*clamp(candleReturn(p,i,6)/.07,0,1)+.15*clamp(candleReturn(p,i,2)/.04,0,1)+.15*clamp((p[i].close/ind.e20[i]-1)/.035,0,1))))}
function signalAt(p,ind,i){if(i<236)return{mode:'NONE'};const c=p[i],prev=p[i-1],r=ind.rs[i]||0,rp=ind.rs[i-1]||0,extension=c.close/ind.e200[i]-1,noChase=candleReturn(p,i,1)<.04&&candleReturn(p,i,6)<.08&&extension<=.035,priceReady=extension>=0&&extension<=.035;let trendArmed=false;for(let j=i-23;j<=i;j++)if((ind.rs[j]??100)<=40)trendArmed=true;const trend=trendArmed&&r>=45&&r<=55&&rp<45&&priceReady&&ind.btcAbove(i)&&ind.btcSlope(i)&&noChase;let shockArmed=false;for(let j=i-35;j<=i;j++)if(candleReturn(p,j,1)<=-.03&&ind.volumeRatio[j]>=3&&(ind.rs[j]??100)<=40)shockArmed=true;const prevExtension=prev.close/ind.e200[i-1]-1,shock=shockArmed&&r>=45&&r<=55&&priceReady&&!(rp>=45&&rp<=55&&prevExtension>=0&&prevExtension<=.035)&&ind.btcAbove(i)&&noChase;let exhaustionArmed=false;for(let j=i-11;j<=i;j++)if(ind.drawdown[j]<=-.06&&ind.shockCount[j]>=3)exhaustionArmed=true;const confirm=(c.close>=ind.e20[i]&&prev.close<ind.e20[i-1])||(ind.breakout[i]&&r>=55&&rp<55),flow=(ind.spotFlow[i]??-1)>=0,market=(ind.market(i)??-1)>=-.02&&(ind.atr[i]??0)>=.007&&(ind.atr[i]??1)<=.035,limit=-.06,exhaustion=exhaustionArmed&&confirm&&r>=43&&r<=58&&flow&&market&&ind.drawdown[i]<=limit,late=lateRisk(p,ind,i),blocked=late>=60&&(trend||shock||exhaustion),mode=blocked?'NONE':exhaustion?'EXHAUSTION':shock?'SHOCK':trend?'TREND':'NONE';return{mode,late,trend,shock,exhaustion}}
function btcCrash(btc1m,start,end){let lo=0;while(lo<btc1m.length&&btc1m[lo].openTime<start)lo++;for(let i=Math.max(3,lo);i<btc1m.length&&btc1m[i].openTime<=end;i++){const old=btc1m[i-3];if(old.close>0&&btc1m[i].close/old.close-1<=-.03)return{time:btc1m[i].closeTime,price:btc1m[i].close}}return null}
function candleIndexAt(candles,time){let lo=0,hi=candles.length-1,ans=-1;while(lo<=hi){const m=(lo+hi)>>1;if(candles[m].openTime<=time){ans=m;lo=m+1}else hi=m-1}return ans}
function simulate(sol30,btc30,btc1m){const ind=indicators(sol30,btc30,sol30),trades=[];let lastEntry=-Infinity,positionUntil=-Infinity,signals=0,expired=0;for(let i=236;i<sol30.length-1;i++){const c=sol30[i];if(c.closeTime<TEST_START||c.closeTime>=TEST_END)continue;if(c.closeTime<positionUntil||c.closeTime-lastEntry<MIN_ENTRY_GAP_MS)continue;const sig=signalAt(sol30,ind,i);if(sig.mode==='NONE')continue;signals++;const limit=c.close*(1-LIMIT_DROP),ttlEnd=c.closeTime+TTL_MS;let fill=null;for(let j=i+1;j<sol30.length&&sol30[j].openTime<=ttlEnd;j++){if(sol30[j].low<=limit){fill={idx:j,time:sol30[j].openTime,price:Math.min(limit,sol30[j].open)};break}}if(!fill){expired++;continue}lastEntry=fill.time;const tp=priceForNet(fill.price,TP_NET),sl=priceForNet(fill.price,STOP_NET),be=priceForNet(fill.price,0),beTrig=priceForNet(fill.price,BE_TRIGGER_NET),holdEnd=fill.time+MAX_HOLD_MS;let armed=false,exit=null;const crash=btcCrash(btc1m,fill.time,holdEnd);for(let j=fill.idx;j<sol30.length&&sol30[j].openTime<=holdEnd;j++){const x=sol30[j];if(crash&&crash.time<=x.closeTime){const k=candleIndexAt(sol30,crash.time);const px=(k>=0?sol30[k].close:x.close)*(1-SLIP);exit={time:crash.time,price:px,why:'BTC_CRASH'};break}if(x.low<=sl){exit={time:x.openTime,price:Math.min(sl,x.open)*(1-SLIP),why:'STOP'};break}if(!armed&&x.high>=beTrig)armed=true;if(armed&&x.low<=be){exit={time:x.openTime,price:Math.min(be,x.open)*(1-SLIP),why:'BE_PROTECT'};break}if(x.high>=tp){exit={time:x.openTime,price:tp,why:'TP'};break}}if(!exit){const k=candleIndexAt(sol30,holdEnd);const x=sol30[Math.min(sol30.length-1,Math.max(fill.idx,k))];exit={time:x.closeTime,price:x.close*(1-SLIP),why:'TIME'}}const pnl=net(fill.price,exit.price);trades.push({signalTime:c.closeTime,mode:sig.mode,entryTime:fill.time,entry:fill.price,exitTime:exit.time,exit:exit.price,why:exit.why,netPct:pnl*100});positionUntil=exit.time;i=Math.max(i,candleIndexAt(sol30,exit.time))}return{signals,expired,trades}}
function metrics(x){const t=x.trades,w=t.filter(z=>z.netPct>0),gp=w.reduce((a,z)=>a+z.netPct,0),gl=-t.filter(z=>z.netPct<=0).reduce((a,z)=>a+z.netPct,0);let eq=1,peak=1,dd=0;for(const z of t){eq*=1+z.netPct/100;peak=Math.max(peak,eq);dd=Math.min(dd,eq/peak-1)}return{signals:x.signals,expired:x.expired,trades:t.length,wins:w.length,winRate:t.length?w.length/t.length*100:0,avgNet:t.length?t.reduce((a,z)=>a+z.netPct,0)/t.length:0,profitFactor:gl?gp/gl:null,compoundPct:(eq-1)*100,maxDdPct:dd*100,exits:Object.fromEntries(['TP','STOP','BE_PROTECT','BTC_CRASH','TIME'].map(k=>[k,t.filter(z=>z.why===k).length]))}}
(async()=>{const [sol30,btc30,btc1m]=await Promise.all([fetchK('SOLUSDT','30m',FETCH_START,FETCH_END),fetchK('BTCUSDT','30m',FETCH_START,FETCH_END),fetchK('BTCUSDT','1m',FETCH_START,FETCH_END)]);const sim=simulate(sol30,btc30,btc1m),m=metrics(sim),result={candidate:'V14-90b41cc55ee1c848',status:'V14 filter reconstruction, not exact hash replay',period:'2026-02-01..2026-03-01 UTC',assumptions:{feeEachSide:FEE,slippageMarket:SLIP,limitDropPct:2.5,ttlMinutes:60,tpNetPct:5,stopNetPct:-15,beTriggerNetPct:3,maxHoldDays:7,minEntryGapHours:18,btcCrash:'-3% / 3m',filters:'reconstructed V14 strict signalAt from pump-pulse-web historical engine; SOL is both primary asset and original SOL market-context slot'},metrics:m,trades:sim.trades};fs.writeFileSync('v14_sol_oos_result.json',JSON.stringify(result,null,2));console.log('V14-90b41cc55ee1c848 — SOL OOS reconstruction');console.log('==============================================');for(const [k,v] of Object.entries(m))console.log(`${k}=${typeof v==='object'?JSON.stringify(v):v}`)})().catch(e=>{console.error(e.stack||e);process.exit(1)});
